# ifndef AUTOMATAMANAGER_HH
# define AUTOMATAMANAGER_HH

# include "Parser.hh"
# include <unordered_set>
# include <unordered_map>
# include <vector>

/**
 * @brief StateType enumeration
 * 
 * Represents the type that a node in the NFA graph can have
 *   - UNIQUE: represents a char transition
 *   - SPLIT: represents two outgoing epsilon transitions from a graph
 *   - MATCH: represents an accepting state with no outgoint transitions
 */
enum StateType { UNIQUE, SPLIT, MATCH };

/**
 * @brief State struct
 * 
 * Represents a node (or state) in the NFA graph. It has 5 attribtues:
 *   - c: char of the outgoing transtion
 *   - type: StateType instance
 *   - first_out: pointer to the next state
 *   - second_out: pointer to second state in case of split 
 *   - id: unique identifier of the state
 * 
 */
struct State {
    char c = 0;                       // char of outgoing transtition
    StateType type;
    State* first_out = nullptr;       // pointer to other state
    State* second_out = nullptr;      // pointer if there is a second transition
    int id;
};

/**
 * @brief Fragment struct
 * 
 * Represents a fragment of the NFA graph. This does not represent the
 * whole graph, only a part. It is useful in building the NFA.
 *   - start: initial state of the fragment
 *   - dangling: set of transitions with no assigned state
 */
struct Fragment {
    State* start;                     // initial node
    std::vector<State**> dangling;    // list of transitions with no assigned state yet
};


/**
 * @brief NFA struct
 * 
 * Represents an NFA graph
 *   - start: initial state
 *   - accept: accepting state
 *   - numStates: number of states
 *   - states: array with the states. This array is necessary so that the
 *             destructor of the States is called correctly.
 */
struct NFA {
    State* start;
    State* accept;
    int numStates = 0;
    std::vector<std::unique_ptr<State>> states;      // list of states
};

struct DState {
    bool accepting = false;
    std::vector<std::unordered_map<char, int>> transitions;
};

struct DFA {
    int start;
    std::vector<DState> states;
};

using SetState = std::unordered_set<State*>;

/**
 * @brief Thompson's NFA
 * 
 * Construction of an NFA as designed in the McNaughton-Yamada-Thompson
 * algorithm. An NFA N generated from a regular expression E using 
 * this process has the following properties:
 *   - N has only one initial state
 *   - N has only one accepting state
 *   - The number of states of A is linear in the size of E
 *   - The number of transitions leaving any state is at most two
 * 
 */
class AutomataManager {

private:
    
    /** @brief next unique id for the following state */
    int nextID = 0;

    /**
     * @brief Generates a new state for the given NFA
     * 
     * @param N nfa being built
     * @param type state type instance
     * @param c char of the state
     * @param out main output of the state
     * @param out1 second output if type is SPLIT, otherwise nullptr
     * @return State* new state with necessary attributes
     */
    State* makeState(NFA& N, StateType type, char c, State* out, State* out1);

    /**
     * @brief Generate NFA from AST
     * 
     * @param nfa input nfa
     * @param ast input asf
     * @return Fragment generated from known tree
     */
    Fragment astToNFA(NFA& nfa, NodePtr& ast);

    /**
     * @brief Computes the Epsilon Closure of a set of states
     * 
     * @param T set of NFA states
     * @return SetState set of states reachable with epsilon transitions
     */
    SetState epsilonClosure(SetState& T);

    /**
     * @brief Simultae NFA by parsing DFA ad-hoc
     * 
     * @param N NFA generated from parse tree
     * @param s string to match
     * @return true if accepting state can be reached by consuming chars of s
     * @return false if any other state is reached
     */
    bool simulateNFA(NFA& N, std::string& s);
    bool simulateDFA(DFA& D, std::string& s);


public:

    /**
     * @brief Construct a new Automata Manager object
     * 
     */
    AutomataManager();

    /**
     * @brief Computes NFA from regular expression
     * 
     * @param ast input ast
     * @return NFA nfa genereated from ast
     */
    NFA regexToNFA(NodePtr& ast);
    DFA nfaToDFA(NFA& n);

    /**
     * @brief Checks if s is accepted by the language
     * generated by N
     * 
     * @param N NFA
     * @param s input string
     * @return true if s is accepted
     * @return false otherwise
     */
    bool isMatch(NFA& N, std::string& s);
    bool isMatch(DFA& D, std::string& s);

};

# endif