# include "RegExParser.hh"
# include <iostream>

int main () {
    RegExParser rp;
    std::string regex, s;
    std::cout << "Input RegEx: ";
    std::cin >> regex;
    rp.parseRegex(regex);
    std::cout << "Input string: ";
    while (std:: cin >> s) {
        if (rp.isAccepted(s))
            std::cout << "String " << s << " belongs to language generated by " << regex << std::endl;
        else
            std::cout << "String does not belong" << std::endl;
        std::cout << "Input string: ";
    }
    
    
}