# include "Parser.hh"
# include "AutomataManager.hh"
# include <iostream>
# include <string>

std::string enumToString(NodeType tp) {
    switch(tp) {
        case 0:
            return "CHAR";
            break;
        case 1:
            return "CONCAT";
            break;
        case 2:
            return "ALT";
            break;
        case 3:
            return "STAR";
            break;
        case 4:
            return "PLUS";
            break;
        case 5:
            return "QUESTION";
            break;
        case 6:
            return "EMPTY";
            break;
        default:
            return "";
            break;
    }
}

std::string enumToString(StateType st) {
    switch(st) {
        case 0:
            return "UNIQUE";
            break;
        case 1:
            return "SPLIT";
            break;
        case 2:
            return "MATCH";
            break;
        default:
            return "";
            break;
    }
}

void printBT(const std::string& prefix, NodePtr& node, bool isLeft)
{
    if (node)
    {
        std::cout << prefix;
        std::cout << (isLeft ? "├──" : "└──" );

        // print the value of the node
        std::cout << enumToString(node->type);
        if (node->type == NodeType::CHAR) std::cout << " " << node->ch;
        std::cout << std::endl;

        // enter the next tree level - left and right branch
        printBT( prefix + (isLeft ? "│   " : "    "), node->left_operand, true);
        printBT( prefix + (isLeft ? "│   " : "    "), node->right_operand, false);
    }
}

void printNFA(const std::string& prefix, State* &node, bool isLeft)
{
    if (node)
    {
        std::cout << prefix;
        std::cout << (isLeft ? "├──" : "└──" );

        // print the value of the node
        std::cout << enumToString(node->type);
        if (node->type == StateType::UNIQUE) std::cout << " " << node->c;
        std::cout << std::endl;

        // enter the next tree level - left and right branch
        printNFA( prefix + (isLeft ? "│   " : "    "), node->first_out, true);
        printNFA( prefix + (isLeft ? "│   " : "    "), node->second_out, false);
    }
}

void printBT(NodePtr& node) {
    printBT("", node, false);
    std::cout << std::endl; 
}

void printNFA(NFA& nfa) {
    printNFA("", nfa.start, false);
    std::cout << std::endl;
}

int main () {
    std::string regex, s;
    std::cout << "Input RegEx: ";
    std::cin >> regex;
    std::cout << std::endl;
    Parser p(regex);
    NodePtr tree = p.parse();
    printBT(tree);
    AutomataManager am;
    auto nfa = am.regexToNFA(tree);
    for (auto s : nfa.states) {
        std::cout << s->id << " " << enumToString(s->type) << " " << s->c << std::endl;
        if (s->first_out) std::cout << " |->" << s->first_out->id << std::endl;
        if (s->second_out) std::cout << " |->" << s->second_out->id << std::endl;
    }
    std::cout << "Input string: ";
    std::cin >> s;
    if (am.isMatch(nfa, s))
        std::cout << "String " << s << " belongs to language generated by " << regex << std::endl;
    else
        std::cout << "String does not belong" << std::endl;
}